name: authcodebase
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  google_sign_in: ^4.5.3 #for authentication with google
  flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0
  http: ^0.12.2
  provider: ^4.3.2+1 #For state management
  firebase_dynamic_links:
    git:
      url: https://github.com/mrmilu/flutterfire
      path: packages/firebase_dynamic_links
      ref: firebase_dynamic_links
  rxdart: ^0.23.1
  flutter_secure_storage: ^3.3.1+1
  package_info: ^0.4.0+13
  random_string: ^2.0.0
  flutter_spinkit: ^4.1.2 #to wait till the network response or data arrives
  google_fonts: ^1.1.0 #fonts
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

